### ISSUE TITLE
[Issue] Mobs will not spawn with dynamic shading on

### ISSUE THREAD

**Issue by xshanaj** [AnOpenSauceDev/Methane-mod#85] opened 2024-02-18 00:48 UTC
# 🔥 Mobs not spawning

## Methane Version 3.5.0
_e.g. Methane - 1.5: 1.20.4

**Comment by xshanaj** [comment] 2024-02-18 00:55
Have done research and found a fix!

**Comment by AnOpenSauceDev** [comment] 2024-02-18 02:54
semi-duplicate of: #80.

This is because of Methane's lighting engine. If you **enable the Legacy "Lighting Engine"**, way less things will query light data, but there still should be a lightmap for mob spawning. Either that, or play your world on a server with a client running Methane.

 If nothing spawns after that, that's a bug with Dynamic Shading that i can't really fix without disabling a lot of what makes Methane fast.

**Comment by xshanaj** [comment] 2024-02-18 08:19
This may be a lot to ask but could you make a version of methane that does disable a lot of things that makes Methane fast, i dont use it for the FPS boost, but rather the look of the game. Simulates optifine internal shaders with old lighting off, and looks wonderful, mainly because optifine is not compatible with forge so there is no hope for me using any other mods with optifine for at least a few more weeks or months lol. But i have found methane to replicate it quite well

**Comment by AnOpenSauceDev** [comment] 2024-02-18 08:51
If you don't want to use Methane as a performance mod, You're probably looking for a mod like [Simply No Shading](https://modrinth.com/mod/simply-no-shading). It has a similar look to Methane.

**Closed by AnOpenSauceDev** 2024-02-18 08:51 UTC
Labels: bug
